# Generated by Django 5.2.10 on 2026-04-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="youtube_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
